_merge: deep
expertises: /consultations/:slug/
persons: /cabinet/:slug/
persons_expertises: /cabinet/expertises/:slug/
persons_statutes: /cabinet/statuts/:slug/

# persons: /equipe/:slug/
# places: /cabinets/:slug/
# persons_places: /equipe/cabinets/:slug/
# persons_expertises: /equipe/expertises/:slug/
# persons_statutes: /equipe/statuts/:slug/
